services:
  - type: static
    name: portfolio-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend-8bk0.onrender.com/api
